project_name        = "pocket-cards"
account_id          = "9999999999999"
slack_url           = "https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
translation_api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ipa_api_key         = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
